version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: octomate-voting-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: octomate_voting
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - voting-network

volumes:
  mongodb_data:

networks:
  voting-network:
    driver: bridge